# Generated by Django 4.1.1 on 2022-09-22 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 22, 19, 15, 53, 595483, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
